### ISSUE TITLE
A issue related to 'site.baseurl'

### ISSUE THREAD

**Issue by liuh886** [klane/jekyllnb#238]
Thanks for your workflow! I run jekyllnb well, the markdown files and pictures are generated correctly. 

The only issue is how the markdown references the pictures, here is an example from [your test file](https://github.com/klane/jekyllnb/blob/master/tests/assets/hello-world.md):

![png]({{ site.baseurl }}/assets/images/hello-world/hello-world_4_0.png){: .center-image }

For me, 'site.baseurl' does not work. I need to delete or change it into 'site.url' or 'relative_url'. I don't exactly know the reason, but [this is a typical problem](https://stackoverflow.com/questions/42450554/jekyll-site-works-locally-but-not-on-github-pages/47530487#47530487).

In my config, baseurl = '''' , which is [the default setting for jekyll website](https://jekyllrb.com/docs/configuration/default/). And relative_url [is a elegant way to prepend baseurl](https://jekyllrb.com/docs/liquid/filters/).

So,  I am wondering does jekyllnb have an option to decide not to use site.baseurl.

**Comment by klane** [comment]
Thank you for your interest @liuh886! I am happy to update jekyllnb to support your use case. I believe I can change the [default filters](https://github.com/klane/jekyllnb/blob/master/jekyllnb/exporter.py#L58-L62) to use `relative_url`.

**Comment by klane** [comment]
@liuh886 can you try branch `feature/relative-url` to see if it resolves your issue?

**Comment by liuh886** [comment]
> 
It works, thanks!

`![png]({{ "/test/img/xsnow_coreg/xsnow_coreg_10_0.png" | relative_url }}){: .center-image }`
